# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Practice_MaLiangCustomBrush' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Practice_MaLiangCustomBrush

  pod 'MaLiang'

end
